// export const REGISTER_LOAD="REGISTER_LOAD"
// export const REGISTER_SUCC="REGISTER_SUCC"
// export const REGISTER_FAIL="REGISTER_FAIL"
// export const LOGIN_LOAD="LOGIN_LOAD"
// export const LOGIN_SUCC="LOGIN_SUCC"
// export const LOGIN_FAIL="LOGIN_FAIL"
export const USER_LOAD = "USER_LOAD";
export const USER_SUCC = "USER_SUCC";
export const USER_FAIL = "USER_FAIL";
